# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    elasticsearch:
        container_name: elastic_test
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        environment:
            - discovery.type=single-node
            - node.name=es01
            - cluster.name=elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - sailelasticsearch:/usr/share/elasticsearch/data
        networks:
            - sail
    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.2
        container_name: kibana_test
        ports:
          - '5601:5601'
          - '9600:9600'
        environment:
          SERVERNAME: kibana
          ELASTICSEARCH_HOSTS: http://172.22.0.1:9200
          ES_JAVA_OPTS: -Xmx512m -Xms512m
        networks:
          - sail
        depends_on:
          - elasticsearch
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sailelasticsearch:
         driver: local
